const express = require("express");
const router = express.Router();
const { createSuperAdmin, updateSuperAdmin, updateSuperAdminBalance, setExposureLimitSuperAdmin, setCreditReferrenceSuperAdmin, lockUnlockSuperAdmin, changePasswordSuperAdmin, declareSessionResult, declareSessionNoResult, unDeclareSessionResult, getBetWallet, declareMatchResult, unDeclareMatchResult, totalProfitLossWallet, totalProfitLossByMatch, getResultBetProfitLoss, getSessionBetProfitLoss, getBetCount } = require("../controllers/fairgameWalletController");
const validator = require("../middleware/joi.validator");
const { CreateSuperAdmin, UpdateSuperAdmin, SuperAdminBalance, SuperAdminExposureLimit, SuperAdminCreditReference, SuperAdminLockUnlock, SuperAdminChangePassword } = require("../validators/fairgameWalletValidator");
const { isUserExist, getCommissionReportsMatch, getCommissionBetPlaced, userList } = require("../controllers/userController");

router.post("/add/user", validator(CreateSuperAdmin), createSuperAdmin);
router.post("/update/user", validator(UpdateSuperAdmin), updateSuperAdmin);
router.post("/update/balance", validator(SuperAdminBalance), updateSuperAdminBalance);
router.post("/update/exposure", validator(SuperAdminExposureLimit), setExposureLimitSuperAdmin);
router.post("/update/creditReference", validator(SuperAdminCreditReference), setCreditReferrenceSuperAdmin);
router.post("/lockUnlock", validator(SuperAdminLockUnlock), lockUnlockSuperAdmin);
router.post("/changePassword", validator(SuperAdminChangePassword), changePasswordSuperAdmin);
router.post("/declare/result/session",  declareSessionResult);
router.post("/declare/noResult/session",  declareSessionNoResult);
router.post("/unDeclare/result/session",  unDeclareSessionResult);
router.post("/declare/result/match",  declareMatchResult);
router.post("/unDeclare/result/match",  unDeclareMatchResult);
router.get("/getBet", getBetWallet);
router.get("/user/exist", isUserExist);
router.post("/total/profitLoss", totalProfitLossWallet);
router.post("/total/matchWise/profitLoss", totalProfitLossByMatch);
router.post("/total/bet/profitLoss", getResultBetProfitLoss);
router.post("/total/session/profitLoss", getSessionBetProfitLoss);
router.get("/commissionMatch/:userId", getCommissionReportsMatch);
router.get("/commissionBetPlaced/:userId", getCommissionBetPlaced);
router.get("/betCounts", getBetCount);
router.get("/user/list", userList);

module.exports = router;
